// <auto-generated />
namespace YummyApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ratinglogsdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ratinglogsdb));
        
        string IMigrationMetadata.Id
        {
            get { return "202209112214359_ratinglogs-db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
